managementCluster:
  name: {{ .ExtraValues.Installation }}
  namespace: org-giantswarm

clusterName: {{ .ClusterName }}
clusterID: {{ .ClusterName }}
provider: capa
global:
  podSecurityStandards:
    enforced: true
enableServiceMutatorWebhook: false
