clusterName: "{{ .ClusterName }}"
organization: "{{ .Organization }}"
userConfig:
  certManager:
      configMap:
        values:
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: "{{ .ClusterName }}-Route53Manager-Role"
          cert-manager-giantswarm-clusterissuer:
            acme:
              http01:
                enabled: false
              dns01:
                route53:
                  enabled: true
                  # TODO Use a variable as soon as it is available.
                  region: "eu-north-1"
                  role: "{{ .ClusterName }}-Route53Manager-Role"
