version: 2.1
orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  test-and-push:
    jobs:
      - architect/push-to-docker:
          context: architect
          name: push-cluster-test-suites-to-quay
          image: "quay.io/giantswarm/cluster-test-suites"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-cluster-test-suites-to-docker
          image: "docker.io/giantswarm/cluster-test-suites"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
