version: 2.1
orbs:
  architect: giantswarm/architect@4.35.6

workflows:
  test-and-push:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
