apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
  namespace: test-storage
spec:
  containers:
    - name: pvc-test-container
      image: nginx
      volumeMounts:
        - name: test-volume
          mountPath: /data
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc
