clusterName: "{{ .ClusterName }}"
clusterDescription: "E2E Test cluster"
organization: "{{ .Organization }}"

baseDomain: test.gigantic.io
kubernetesVersion: v1.22.9+vmware.1

cloudDirector:
  org: giantswarm
  ovdc: vDC 73640
  site: https://vmware.ikoula.com
  ovdcNetwork: capvcd-192.168.52.0

cloudProvider:
  enableVirtualServiceSharedIP: false
  oneArm:
    enabled: true
        
controlPlane:
  catalog: giantswarm
  replicas: 3
  sizingPolicy: m1.large
  template: ubuntu-2004-kube-v1.22.9

connectivity:
  network:
    loadBalancers:
      vipSubnet: "178.170.32.1/24"

nodeClasses:
  default:
    catalog: giantswarm
    sizingPolicy: m1.large
    template: ubuntu-2004-kube-v1.22.9
nodePools:
  worker:
    class: default
    replicas: 2
proxy:
  enabled: false
  secretName: ""
userContext:
  secretRef:
    secretName: vcd-credentials
    useSecretRef: true
