baseDomain: test.gigantic.io
controlPlane:
  catalog: giantswarm
  replicas: 3
  sizingPolicy: m1.large
  template: ubuntu-2004-kube-v1.22.9
connectivity:
  network:
    loadBalancers:
      vipSubnet: "178.170.32.1/24"
  proxy:
    enabled: false
nodePools:
  worker:
    class: default
    replicas: 2
providerSpecific:
  org: giantswarm
  ovdc: vDC 73640
  site: https://vmware.ikoula.com
  ovdcNetwork: capvcd-192.168.52.0
  cloudProviderInterface:
    enableVirtualServiceSharedIP: false
    oneArm:
      enabled: true
  nodeClasses:
    default:
      catalog: giantswarm
      sizingPolicy: m1.large
      template: ubuntu-2004-kube-v1.22.9
  userContext:
    secretRef:
      secretName: vcd-credentials
metadata:
  description: "E2E Test cluster"
  organization: "{{ .Organization }}"
internal:
  kubernetesVersion: v1.22.9+vmware.1
