baseDomain: test.gigantic.io
controlPlane:
  catalog: giantswarm
  replicas: 3
  sizingPolicy: m1.large
  template: ubuntu-2004-kube-v1.24.10
connectivity:
  network:
    loadBalancers:
      vipSubnet: "10.205.9.254/24"
  proxy:
    enabled: true
nodePools:
  worker:
    class: default
    replicas: 2
providerSpecific:
  cloudProviderInterface: {}
  org: GIANT_SWARM
  ovdc: Org-GIANT-SWARM
  site: "https://cd.neoedge.cloud"
  ovdcNetwork: GS-ISOLATED
  nodeClasses:
    default:
      catalog: giantswarm
      sizingPolicy: m1.large
      template: ubuntu-2004-kube-v1.24.10
  userContext:
    secretRef:
      secretName: vcd-credentials
metadata:
  description: "E2E Test cluster"
  organization: "{{ .Organization }}"
internal:
  kubernetesVersion: v1.24.10+vmware.1
