# Values provided here merge on top of the default values found in https://github.com/giantswarm/cluster-standup-teardown
global:
  providerSpecific:
    awsClusterRoleIdentityName: giantswarm-grizzly-wc-e2e-eks
cluster:
  providerIntegration:
    apps:
      certExporter:
        enable: true
      certManager:
        enable: true
      chartOperatorExtensions:
        enable: true
      cilium:
        enable: true
      ciliumServiceMonitors:
        enable: true
      clusterAutoscaler:
        enable: true
      coreDns:
        enable: true
      coreDnsExtensions:
        enable: true
      externalDns:
        enable: true
      k8sDnsNodeCache:
        enable: true
      metricsServer:
        enable: true
      netExporter:
        enable: true
      networkPolicies:
        enable: true
      nodeExporter:
        enable: true
      observabilityBundle:
        enable: true
      observabilityPolicies:
        enable: true
      rbacBootstrap:
        enable: true
      securityBundle:
        enable: true
      verticalPodAutoscaler:
        enable: true
      verticalPodAutoscalerCrd:
        enable: true
