metadata:
  name: "{{ .ClusterName }}"
  description: "E2E Test cluster"
  organization: "{{ .Organization }}"

controlPlane:
  # disable logging to save cost
  logging:
    apiServer: false
    audit: false
    authenticator: false
    controllerManager: false

# We need to pass the node pools otherwise the test called "has all the worker nodes running" will fail because it
# expects to find the number of worker nodes in the helm values, but the value is not there if don't pass it, as it's
# defaulted in the chart template.
# @TODO: https://github.com/giantswarm/giantswarm/issues/28063
nodePools:
  pool0:
    maxSize: 3
    minSize: 3
    rootVolumeSizeGB: 25