global:
  metadata:
    name: "{{ .ClusterName }}"
    description: "E2E Test cluster"
    organization: "{{ .Organization }}"

  controlPlane:
    # disable logging to save cost
    logging:
      apiServer: false
      audit: false
      authenticator: false
      controllerManager: false

  # We need to pass the node pools otherwise the test called "has all the worker nodes running" will fail because it
  # expects to find the number of worker nodes in the helm values, but the value is not there if don't pass it, as it's
  # defaulted in the chart template.
  # @TODO: https://github.com/giantswarm/giantswarm/issues/28063
  nodePools:
    # We are using a name with 10 chars which is the max number of characters allowed by our kyverno policies.
    nodepool-0:
      instanceType: r6i.xlarge
      maxSize: 3
      minSize: 2
      rootVolumeSizeGB: 25
