# Values provided here merge on top of the default values found in https://github.com/giantswarm/cluster-standup-teardown
global:
  providerSpecific:
    awsClusterRoleIdentityName: giantswarm-grizzly-wc-e2e-eks
cluster:
  providerIntegration:
    apps:
      coreDns:
        enable: true
      observabilityBundle:
        enable: true
      securityBundle:
        enable: true
      certExporter:
        enable: true
      clusterAutoscaler:
        enable: true
      nodeExporter:
        enable: true
      verticalPodAutoscaler:
        enable: true
      verticalPodAutoscalerCrd:
        enable: true
