# Values provided here merge on top of the default values found in https://github.com/giantswarm/cluster-standup-teardown
userConfig:
  certManager:
    configMap:
      values:
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "{{ .ClusterName }}-CertManager-Role"
        giantSwarmClusterIssuer:
          acme:
            http01:
              enabled: false
            dns01:
              route53:
                enabled: true
                # TODO Use a variable as soon as it is available.
                region: "eu-north-1"
