baseDomain: test.gigantic.io
controlPlane:
  catalog: giantswarm
  # HA is disabled temporarily due to
  # https://github.com/giantswarm/giantswarm/issues/29353
  replicas: 1
  sizingPolicy: m1.large
  template: ubuntu-2004-kube-v1.25.13
  oidc:
    clientId: "dex-k8s-authenticator"
    groupsClaim: "groups"
    issuerUrl: "https://dex.gerbil.test.gigantic.io"
    usernameClaim: "email"
connectivity:
  network:
    loadBalancers:
      vipSubnet: "10.205.9.254/24"
  ntp:
    servers:
      - "10.205.105.253"
  proxy:
    enabled: true
nodePools:
  worker:
    class: default
    replicas: 2
providerSpecific:
  org: GIANT_SWARM
  ovdc: Org-GIANT-SWARM
  site: "https://cd.neoedge.cloud"
  ovdcNetwork: GS-ISOLATED
  nodeClasses:
    default:
      catalog: giantswarm
      sizingPolicy: m1.large
      template: ubuntu-2004-kube-v1.25.13
  userContext:
    secretRef:
      secretName: vcd-credentials
metadata:
  description: "E2E Test cluster"
  organization: "{{ .Organization }}"
internal:
  kubernetesVersion: v1.25.13+vmware.1
