# Values provided here merge on top of the default values found in https://github.com/giantswarm/cluster-standup-teardown
global:
  providerSpecific:
    awsClusterRoleIdentityName: team-tinkerers-giantswarm-grizzly-wc-e2e
  connectivity:
    # These two settings enable Cilium ENI mode
    network:
      pods:
        cidrBlocks:
          - 10.1.0.0/16
    cilium:
      ipamMode: eni
