# Values provided here merge on top of the default values found in https://github.com/giantswarm/cluster-standup-teardown
global:
  providerSpecific:
    awsClusterRoleIdentityName: giantswarm-grizzly-wc-e2e
    nodeTerminationHandlerEnabled: false # https://github.com/giantswarm/giantswarm/issues/32656

  # Mixed node pools: 1 ASG-based + 1 Karpenter-based
  # This reflects production usage where customers run both pool types
  nodePools:
    np-karpntr:
      type: karpenter
      rootVolumeSizeGB: 15
      libVolumeSizeGB: 30
      logVolumeSizeGB: 10
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: NotIn
          values:
            - t3
            - t3a
            - t2
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - "4"
            - "8"
            - "16"
            - "32"
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values:
            - nitro
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
