clusterDescription: "E2E Test cluster"
organization: "{{ .Organization }}"

baseDomain: test.gigantic.io
cluster:
  kubernetesVersion: "v1.24.11"

controlPlane:
  replicas: 1
  catalog: "giantswarm"
  image:
    repository: registry.k8s.io
  machineTemplate:
    template: ubuntu-2004-kube-v1.24.11
    cloneMode: "linkedClone"
    diskGiB: 50
    numCPUs: 4
    memoryMiB: 8096
    resourcePool: "grasshopper"
    network:
      devices:
      - networkName: 'grasshopper-capv'
        dhcp4: true

connectivity:
  network:
    controlPlaneEndpoint:
      host: "10.10.222.231"  # [string] Manually select an IP for kube API.
      port: 6443
    loadBalancers:
      cidrBlocks:
      - "10.10.222.232/30"

nodeClasses:
  default:
    template: ubuntu-2004-kube-v1.24.11
    cloneMode: "linkedClone"
    diskGiB: 50
    numCPUs: 6
    memoryMiB: 16896
    resourcePool: "grasshopper"
    network:
      devices:
      - networkName: 'grasshopper-capv'
        dhcp4: true

nodePools:
  worker:
    class: "default"
    replicas: 2
