clusterDescription: "E2E Test cluster"
organization: "{{ .Organization }}"

baseDomain: test.gigantic.io
cluster:
  kubernetesVersion: "v1.24.11"

controlPlane:
  replicas: 1
  catalog: "giantswarm"
  image:
    repository: registry.k8s.io
  machineTemplate:
    template: flatcar-stable-3602.2.1-kube-v1.24.12-gs
    cloneMode: "linkedClone"
    diskGiB: 50
    numCPUs: 4
    memoryMiB: 8096
    resourcePool: "grasshopper"
    network:
      devices:
      - networkName: 'grasshopper-capv'
        dhcp4: true

connectivity:
  bastion:
    enabled: true
  network:
    allowAllEgress: true
    controlPlaneEndpoint:
      host: ""  # [string] Manually select an IP for kube API. "" for auto selection from the ipPoolName pool.
      port: 6443
      ipPoolName: "wc-cp-ips"  # [string] Ip for control plane will be drawn from this GlobalInClusterIPPool (for gcapeverde it's 10.10.222.232 - 10.10.222.238 inclusive)
    loadBalancers:
      ipPoolName: "svc-lb-ips"  # [string] 1 ip for WC's kubevip will be drawn from this GlobalInClusterIPPool (for gcapeverde it's 10.10.222.245 - 10.10.222.249 inclusive)
      cidrBlocks: []

nodeClasses:
  default:
    template: flatcar-stable-3602.2.1-kube-v1.24.12-gs
    cloneMode: "linkedClone"
    diskGiB: 50
    numCPUs: 6
    memoryMiB: 16896
    resourcePool: "grasshopper"
    network:
      devices:
      - networkName: 'grasshopper-capv'
        dhcp4: true

nodePools:
  worker:
    class: "default"
    replicas: 2
